### ISSUE TITLE
cargo build --features tokio fails to build on windows

### ISSUE THREAD

**Issue by Trolldemorted** [ebfull/pcap#120] opened 2020-08-28 02:35 UTC
```
C:\Users\Benni\repositories\pcap>cargo test  --features tokio
   Compiling pcap v0.7.0 (C:\Users\Benni\repositories\pcap)
error[E0432]: unresolved import `mio::unix`
 --> src\tokio.rs:3:10
  |
3 | use mio::unix::EventedFd;
  |          ^^^^ could not find `unix` in `mio`

error[E0412]: cannot find type `RawFd` in this scope
  --> src\tokio.rs:16:9
   |
16 |     fd: RawFd
   |         ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> src\tokio.rs:49:37
   |
49 |     pub fn new(cap: Capture<T>, fd: RawFd, handle: &tokio_core::reactor::Handle, codec: C) -> Result<PacketStream<T, C>, Error> {
   |                                     ^^^^^ not found in this scope

error[E0432]: unresolved import `mio::unix`
 --> src\tokio.rs:3:10
  |
3 | use mio::unix::EventedFd;
  |          ^^^^ could not find `unix` in `mio`

error[E0412]: cannot find type `RawFd` in this scope
  --> src\tokio.rs:16:9
   |
16 |     fd: RawFd
   |         ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> src\tokio.rs:49:37
   |
49 |     pub fn new(cap: Capture<T>, fd: RawFd, handle: &tokio_core::reactor::Handle, codec: C) -> Result<PacketStream<T, C>, Error> {
   |                                     ^^^^^ not found in this scope

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `pcap`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `pcap`.

To learn more, run the command again with --verbose.
```

**Comment by sekineh** [comment] 2020-08-28 06:05
I got the same error on my machine!

Oh in previous CI, error was ignored.... 
https://github.com/ebfull/pcap/runs/1039308893
![image](https://user-images.githubusercontent.com/3956266/91527002-d42aaf00-e93f-11ea-85c2-db1bac30a80d.png)

**Comment by sekineh** [comment] 2020-08-28 06:31
I don't think the whole `tokio.rs` is relevant to windows platform.
Just `cfg`ing out might be the solution?

**Comment by Wojtek242** [comment] 2020-08-28 08:10
As is, there is no way the `tokio` feature will work on WIndows to the usage of unix file descriptors and I don't think it ever was. I would exclude the `tokio` feature from WIndows builds until such support is added.

**Comment by Trolldemorted** [comment] 2020-08-28 10:43
>As is, there is no way the tokio feature will work on WIndows to the usage of unix file descriptors and I don't think it ever was.

npcap has[ pcap_getevent](https://nmap.org/npcap/guide/npcap-devguide.html#npcap-api), and there are some comments that portable code should use [pcap_loop/pcap_dispatch](https://github.com/nmap/npcap/issues/161) instead. Nevertheless I have never used any of that, and I don't have enough insight on tokio to know which polling method it uses (select won't work with pcap_getevent I think).

>I would exclude the tokio feature from WIndows builds until such support is added.

yeah, it doesn't look like it ever worked /shrug

**Comment by Wojtek242** [comment] 2020-09-09 21:16
Closing, because technically not a bug as it never worked. If the `capture-stream` feature (the feature that used to be called `tokio`) is desired on Windows, please open a new issue and reference this one.

**Closed by Wojtek242** 2020-09-09 21:16 UTC
Labels: wontfix
