### ISSUE TITLE
easylisten example hangs on macOS

### ISSUE THREAD

**Issue by vignesh-sankaran** [ebfull/pcap#93] opened 2018-02-05 07:08 UTC
I am currently running macOS 10.13, and the easylisten example hangs when attempting to capture packets and print them out. This is after I ran `sudo chmod o+r /dev/bpf*` to resolve an issue regarding BPF permissions.

**Comment by tnull** [comment] 2020-02-18 14:56
Even though this question is very old now, this could spare the next person some time: the issue seems to be a known bug. See the note at [Crates.io](https://crates.io/crates/pcap):

> Note: A timeout of zero may cause pcap::Capture::next to hang and never return (because it waits for the timeout to expire before returning). This can be fixed by using a non-zero timeout (as the libpcap manual recommends) and calling pcap::Capture::next in a loop.

**Comment by sekineh** [comment] 2020-09-11 09:38
It's not a bug that it blocks until receiving packet.

I'd propose adding timeout call to the `easylisten` example to endorse the use of that usage.

**Comment by Wojtek242** [comment] 2020-09-13 11:01
Sounds reasonable, but I don't have a mac to verify this against once fixed and I don't think examples are run as part of CI (they are compiled at least though). I marked as `need help` as I assume @sekineh also doesn't use a mac (but I may be wrong).

**Comment by sekineh** [comment] 2020-09-15 08:36
I have two Mac but don't use them for daily development.
I today launched older Mac with El Capitan (10.11.6) and ran `rustup update` to get rustc 1.46.
Then I ran `cargo build --examples; sudo cargo run --example easylisten`.

There are three potential issues.

## (trivial) Device lookup problem

On my Mac, `lookup()` returned "en0" (RJ-45) which is not connected.
You should supply busy interface manually to capture packets.
```
let mut cap = Capture::from_device("en1").unwrap(); // WiFi interface
```

## `Capture::next()` waits forever

- Expected: When a packet arrives, `Capture::next()` returns.
- Observed: `Capture::next()` waits forever even after a packet has arrived.

I needed to call `.timeout()` to workaround this.
This might be a bug on `libpcap` side.

## `Capture::next()` behaviour when `.timeout(5000)` was supplied.

- Expected: When a packet arrives, `Capture::next()` returns.
- Actual: ~5000ms later, `Capture::next()` returns a packet.

I don't think it's a usual _timeout_ behavior. It's a _timer_ behavior.

**Comment by Wojtek242** [comment] 2020-09-19 20:51
Awesome, thanks for investigating!

This looks like it's related to immediate mode. According to  https://www.tcpdump.org/manpages/pcap_set_immediate_mode.3pcap.html. Interfaces not in immediate mode will not deliver packets immediately. The link above does not define what libpcap waits for, but I assume it will only deliver packets once its internal buffer fills up or the timer expires (which is what you see).

From the "Backwards compatibility" section it is not fully clear to me if MacOS always starts in immediate mode. It seems that prior to libpcap 1.5.0 it was NOT in immediate mode by default, but it is unclear if captures start in immediate mode after 1.5.0. The sentence "On other platforms, capture devices are always in immediate mode." suggests they do in which case the problem you see above would not be due to immediate mode. 

What version of libpcap were you testing against?

Immediate mode was precisely the reason why I started with my own fork and I was planning on adding support for immediate mode after the build-time config flags get merged. Perhaps we should try again when adding immediate mode support?

**Comment by Wojtek242** [comment] 2020-09-19 20:59
You can always try quickly uncommenting `pcap_set_immediate_mode` in `raw.rs` and calling it on the capture prior to receiving the packet to see if it solves the problem on the mac.

Having said that if it was related to immediate mode, this issue should also affect Linux and I don't see it happening on Linux.

**Comment by Wojtek242** [comment] 2020-09-19 21:13
I've pushed code to the branch `hack-immediate-mode` which you can use to test if it is immediate mode. Make sure you have libpcap >= 1.5.0. My quick testing on linux showed that indeed actually easylisten may also hang on linux, but it does not hang with immediate mode set.

**Closed** 2020-10-17 16:11 UTC
Labels: bug, help wanted, needs repro

**Comment by Wojtek242** [comment] 2020-10-17 16:12
Should now be fixed now that immediate mode support has been added to all the examples. Please re-open if that is not the case.
